import Link from 'next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Nav = () => {
  return (
    <header className="bg-primary h-[3rem] text flex-row flex">
      {[
        ['Home', '/'],
        ['Projects', '/projects'],
      ].map(([title, path]) => (
        <Link
          key={title}
          className="hover:font-bold cursor-pointer h-full ml-5 leading-[3rem]"
          href={path}
        >
          {title}
        </Link>
      ))}
    </header>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-background text-white'}>
        <Nav />

        <main className="h-screen flex items-center flex-col color-primary px-8 md:px-[20rem] mt-8">
          {children}
        </main>
      </body>
    </html>
  )
}
